### ISSUE TITLE
Errors in Nextcloud logs - File doesn't exist

### ISSUE THREAD

**Issue by blacks0cks1** [nextcloud/text2image_stablediffusion#20]
Nextcloud version - [Nextcloud Hub 8] (29.0.7)

Installed Models but getting below error  "File doesn't exist" .. 

{"reqId":"Mkdi1ufRgVZ7Xf2iBb7j","level":2,"time":"2024-09-18T10:22:20+00:00","remoteAddr":"","user":"--","app":"text2image_stablediffusion","method":"","url":"--","message":"Stable diffusion process failed with exit code \"1\": /var/www/html/nextcloud/apps/text2image_stablediffusion/node_modules/onnxruntime-node/dist/backend.js:24\n            __classPrivateFieldGet(this, _OnnxruntimeSessionHandler_inferenceSession, \"f\").loadModel(pathOrBuffer, options);\n                                                                                           ^\n\nError: Load model from /var/www/html/nextcloud/apps/text2image_stablediffusion/src/../models/stable-diffusion-xl/text_encoder/model.onnx failed:Load model /var/www/html/nextcloud/apps/text2image_stablediffusion/src/../models/stable-diffusion-xl/text_encoder/model.onnx failed. File doesn't exist\n    at new OnnxruntimeSessionHandler (/var/www/html/nextcloud/apps/text2image_stablediffusion/node_modules/onnxruntime-node/dist/backend.js:24:92)\n    at /var/www/html/nextcloud/apps/text2image_stablediffusion/node_modules/onnxruntime-node/dist/backend.js:64:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\n\nNode.js v18.12.1\n","userAgent":"--","version":"29.0.7.1","data":{"app":"text2image_stablediffusion"}}

**Comment by ralfi** [comment]
same here, seems to me wrong path syntax

**Comment by oli-ver** [comment]
Same here, the path that it seems to check is the following:

`/var/www/html/nextcloud/apps/text2image_stablediffusion/src/../models/`

But the models are here (in a Nextcloud docker context):

`/var/www/html/custom_apps/text2image_stablediffusion/models`

**Comment by oli-ver** [comment]
Even when fixing the path, afterwards the generated image cannot be found on the tmp path that was generated. Did anyone get this app working in a Nextcloud v30?

```
Running array ( 0 => '/var/www/html/custom_apps/text2image_stablediffusion/bin/node', 1 => '/var/www/html/custom_apps/text2image_stablediffusion/src/stablediffusion.mjs', 2 => 'tree landscape pieceful', 3 => 1, 4 => '/tmp/oc_tmp_x3B8c6-folder/', ) 
A TaskProcessing core:text2image task with id 50 failed with the following message: Stable diffusion process failed 
```

Not much more information to be found. I checked the tmp folder in the nextcloud container, no folder or files to be found under that name. I checked in what I tried until now on https://github.com/oli-ver/text2image_stablediffusion/tree/fix_path. Only temporary fixes, but for now I would like to see it working in general :)
